ARG TARGETARCH
ARG NGINX_VERSION=1.23.2-alpine

FROM nginx:${NGINX_VERSION}  


COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/templates /etc/nginx/templates


ENV NGINX_RUN_USER=1000 
ENV NGINX_PID_FILE=/var/run/nginx.pid
ENV NGINX_LISTEN_PORT=80
ENV NGINX_PUB_DIR=public
ENV NGINX_FASTCGI_PASS="localhost:9000"
ENV NGINX_FASTCGI_BUFFER_SIZE=32k
ENV NGINX_FASTCGI_BUFFERS="8 16k"
ENV NGINX_CLIENT_MAX_BODY_SIZE=200m
ENV NGINX_KEEPALIVE_TIMEOUT=25
ENV NGINX_WORKER_PROCESSES=auto 
ENV NGINX_WORKER_CONNECTIONS=4096
ENV NGINX_WORKER_RLIMIT_NOFILE=4400
ENV NGINX_MULTI_ACCEPT=on
ENV NGINX_SERVER_TOKENS=off
ENV NGINX_SENDFILE=on
ENV NGINX_TCP_NOPUSH=on
ENV NGINX_TCP_NODELAY=off
ENV NGINX_GZIP=on
ENV NGINX_GZIP_HTTP_VERSION="1.0"
ENV NGINX_GZIP_COMP_LEVEL=5
ENV NGINX_GZIP_MIN_LENGTH=256
ENV NGINX_GZIP_PROXIED=any
ENV NGINX_GZIP_VARY=on

EXPOSE 80

 
